name: Deploy to Cloudflare Pages

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer Node.js et npm
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.7
          cache: 'npm'

      - name: Vérifier la version de Node.js et npm
        run: |
          node -v
          npm -v

      - name: Installer les dépendances
        run: npm install

      - name: Build static files
        run: npm run generate

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.CLOUDFLARE_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$deploy_url"
